### PR TITLE
[fix Issus 56] Update example file name

### PR DESCRIPTION
**Pull request by darionyaphet**

### CODE REVIEW

**Comment by manuzhang** [comment]
@darionyaphet thanks, could you cherry pick bc50c5b against master ?

**Comment by darionyaphet** [comment]
It seems I push this request from my branch `issus_56` . Will cherry pick this PR to master branch and push again ?

**Comment by manuzhang** [comment]
You may create a clean branch against latest master and cherry pick just the commit bc50c5b.

**Comment by darionyaphet** [comment]
Sorry , I don't know what you mean . 

Because this pull request contain two commit ? I will merge the pull requests into one

**Comment by stanleyxu2005** [comment]
Please make sure:
1. Only one commit per PR
2. The commit message should be "fix #56: description of the commit"

**Comment by darionyaphet** [comment]
@stanleyxu2005 thank you ~~

**Comment by clockfly** [comment]
@darionyaphet 

Thanks for your contribution. 

+1

**Pull request merged**
